SELECT HP.PARTY_NAME SUPPLIER_NAME
	, HPS.PARTY_SITE_NAME
	, HL.COUNTRY
	, HL.ADDRESS1
	, HL.COUNTY
	, HL.CITY
	, HL.STATE
	, HL.POSTAL_CODE
	, HCP.PHONE_COUNTRY_CODE
	, HCP.PHONE_AREA_CODE
	, HCP.PHONE_NUMBER
	, PSAV.ADDRESS_PURPOSE_RFQ_OR_BIDDING
	, PSAV.ADDRESS_PURPOSE_ORDERING
	, PSAV.ADDRESS_PURPOSE_REMIT_TO
	, PSAV.EMAIL_ADDRESS
FROM POZ_SUPPLIERS PS
	, HZ_PARTIES HP
	, POZ_SUPPLIER_SITES_ALL_M PSSAM
	, HZ_PARTY_SITES HPS
	, HZ_LOCATIONS HL
	, HZ_CONTACT_POINTS HCP
	, POZ_SUPPLIER_ADDRESS_V PSAV
WHERE 1 = 1
	AND PS.PARTY_ID = HP.PARTY_ID
	AND PS.VENDOR_ID = PSSAM.VENDOR_ID
	AND PSSAM.PARTY_SITE_ID = HPS.PARTY_SITE_ID
	AND HPS.STATUS = 'A'
	AND HPS.LOCATION_ID = HL.LOCATION_ID
	AND HPS.PARTY_SITE_ID = HCP.OWNER_TABLE_ID(+)
	AND HCP.OWNER_TABLE_NAME(+) = 'HZ_PARTY_SITES'	
	AND HPS.PARTY_SITE_ID = PSAV.PARTY_SITE_ID
	--AND ROWNUM < 100
	--AND HP.PARTY_NAME = 'AMERICAN EXPRESS COMPANY MEXICO SA DE CV' 
	--AND HP.PARTY_NAME IN(:P_Proveedor)
    AND (HP.PARTY_NAME IN (:P_Proveedor) OR 'ALL' IN (:P_Proveedor || 'All'))


ORDER BY HP.PARTY_NAME ASC
