SELECT HP.PARTY_NAME SUPPLIER_NAME
	, PRC_BU.BU_NAME PROCUREMENT_BU 
	, HPS.PARTY_SITE_NAME ADRRESS_NAME
	, PSSAM.VENDOR_SITE_CODE SUPPLIER_SITE
	, '' SUPPLIER_SITE_NEW
	, PSSAM.INACTIVE_DATE
	, PSSAM.RFQ_ONLY_SITE_FLAG SOURCING_ONLY
	, PSSAM.PURCHASING_SITE_FLAG PURCHASING
	, PSSAM.PCARD_SITE_FLAG PROCUERMENT_FLAG
	, PSSAM.PAY_SITE_FLAG PAY
	, PSSAM.PRIMARY_PAY_SITE_FLAG PRIMARY_PAY
	, PSSAM.TAX_REPORTING_SITE_FLAG INCOME_TAX_REPORTING_SITE
	, PS.CUSTOMER_NUM CUSTOMER_NUMBER
	, PSSAM.B2B_COMM_METHOD_CODE ENABLE_B2B_MESSAGING
	, PSSAM.HOLD_FLAG HOLD_ALL_NEW_PURCHASING_DOCUMENTS
	, PSSAM.PURCHASING_HOLD_REASON 
	, PSSAM.PAYMENT_CURRENCY_CODE PAYMENT_CURRENCY
	, PSSAM.PAYMENT_PRIORITY
	, PSSAM.PAY_GROUP_LOOKUP_CODE PAY_GROUP
	, PSSAM.HOLD_UNMATCHED_INVOICES_FLAG
	, ATT.NAME PAYMENT_TERMS
	, PSSAM.TERMS_DATE_BASIS
	, PSSAM.PAY_DATE_BASIS_LOOKUP_CODE PAY_DATE_BASIS
	, PSSAM.BANK_CHARGE_DEDUCTION_TYPE
	, PSSAM.ALWAYS_TAKE_DISC_FLAG
	, PSSAM.EXCLUDE_FREIGHT_FROM_DISCOUNT
	, PSSAM.EXCLUDE_TAX_FROM_DISCOUNT
	, PSSAM.AUTO_CALCULATE_INTEREST_FLAG CREATE_INTEREST_INVOICES
	, IEPA.DEFAULT_PAYMENT_METHOD_CODE
	, IEPA.DELIVERY_CHANNEL_CODE
	, IEPA.BANK_INSTRUCTION_DETAILS
	, IEPA.BANK_INSTRUCTION1_CODE
	, IEPA.BANK_INSTRUCTION2_CODE
FROM POZ_SUPPLIERS PS
	, HZ_PARTIES HP
	, POZ_SUPPLIER_SITES_ALL_M PSSAM
	, FUN_ALL_BUSINESS_UNITS_V PRC_BU
	, HZ_PARTY_SITES HPS
	, AP_TERMS_B ATB
	, AP_TERMS_TL ATT
	, IBY_EXTERNAL_PAYEES_ALL IEPA
WHERE 1 = 1
	AND PS.PARTY_ID = HP.PARTY_ID
	AND PS.VENDOR_ID = PSSAM.VENDOR_ID
	AND PSSAM.PRC_BU_ID = PRC_BU.BU_ID
	AND PSSAM.PARTY_SITE_ID = HPS.PARTY_SITE_ID
	AND HPS.STATUS = 'A'
	AND PSSAM.TERMS_ID = ATB.TERM_ID(+)
	AND ATB.TERM_ID = ATT.TERM_ID(+)
	AND ATT.LANGUAGE(+) = USERENV('LANG')
	--AND ROWNUM < 100
	--AND PSSAM.PARTY_SITE_ID = IEPA.PARTY_SITE_ID
	AND PSSAM.VENDOR_SITE_ID = IEPA.SUPPLIER_SITE_ID(+)
	--AND HP.PARTY_NAME = 'AMERICAN EXPRESS COMPANY MEXICO SA DE CV' 
	--AND HP.PARTY_NAME IN(:P_Proveedor)
	AND (HP.PARTY_NAME IN (:P_Proveedor) OR 'ALL' IN (:P_Proveedor || 'All'))

ORDER BY HP.PARTY_NAME ASC