SELECT HP.PARTY_NAME SUPPLIER_NAME
	, PSV.VENDOR_NAME_ALT ALTERNATE_NAME
	, PS.SEGMENT1 SUPPLIER_NUMBER
	, PS.ORGANIZATION_TYPE_LOOKUP_CODE TAX_ORGANIZATION_TYPE
	, PS.VENDOR_TYPE_LOOKUP_CODE SUPPLIER_TYPE
	, PS.END_DATE_ACTIVE INACTIVE_DATE
	, PS.BUSINESS_RELATIONSHIP
	, PS.CUSTOMER_NUM CUSTOMER_NUMBER
	, PS.TAXPAYER_COUNTRY
	, PSP.INCOME_TAX_ID TAXPAYER_ID
	, PS.ALLOW_AWT_FLAG USE_WITHHOLDING_TAX
	, ZR.REGISTRATION_NUMBER RAX_REGISTRATION_NUMBER
	, PS.ATTRIBUTE1
	, PS.ATTRIBUTE2
	, PS.ATTRIBUTE3
	, PS.ATTRIBUTE4
	, PS.ATTRIBUTE5
	, PS.ATTRIBUTE6
	, PS.ATTRIBUTE7
	, PS.ATTRIBUTE8
	, IEPPM.PAYMENT_METHOD_CODE
	--, PSSAM.TERMS_ID
	, PS.VENDOR_ID
FROM POZ_SUPPLIERS PS
	, HZ_PARTIES HP
	, POZ_SUPPLIERS_V PSV
	, POZ_SUPPLIERS_PII PSP
	, ZX_PARTY_TAX_PROFILE ZPTP
	, ZX_REGISTRATIONS ZR
	, IBY_EXTERNAL_PAYEES_ALL IEPA
	, IBY_EXT_PARTY_PMT_MTHDS IEPPM
	--, POZ_SUPPLIER_SITES_ALL_M PSSAM
WHERE 1 = 1
	AND PS.PARTY_ID = HP.PARTY_ID
	AND PS.VENDOR_ID = PSV.VENDOR_ID
	AND PS.VENDOR_ID = PSP.VENDOR_ID
	AND HP.PARTY_ID = ZPTP.PARTY_ID(+)
	AND ZPTP.PARTY_TAX_PROFILE_ID = ZR.PARTY_TAX_PROFILE_ID(+)
	AND PSV.PARTY_ID = IEPA.PAYEE_PARTY_ID
	AND IEPA.ext_payee_id = IEPPM.ext_pmt_party_id(+)
	AND IEPPM.PRIMARY_FLAG = 'Y'
	AND PS.END_DATE_ACTIVE IS NULL
	AND ZPTP.PARTY_TYPE_CODE = 'THIRD_PARTY'
	AND SYSDATE BETWEEN IEPPM.START_DATE AND IEPPM.END_DATE
    AND (HP.PARTY_NAME IN (:P_Proveedor) OR 'ALL' IN (:P_Proveedor || 'All'))
	--AND (PAPF.PERSON_NUMBER IN (:P_NUMERO_PERSONA) OR 'All' IN (:P_NUMERO_PERSONA || 'All'))

	--AND ROWNUM < 100
	--AND PS.VENDOR_ID = PSSAM.VENDOR_ID
	--AND HP.PARTY_NAME IN (:P_Proveedor) --'AMERICAN EXPRESS COMPANY MEXICO SA DE CV' 

ORDER BY HP.PARTY_NAME ASC

