SELECT PSV.VENDOR_NAME
    , PSSV.VENDOR_SITE_CODE
    , (SELECT BU_NAME FROM FUN_ALL_BUSINESS_UNITS_V WHERE BU_ID = PSSAM.PRC_BU_ID) PROCUREMENT_BU
    , (SELECT BU_NAME FROM FUN_ALL_BUSINESS_UNITS_V WHERE BU_ID = PSAAM.BU_ID) CLIENT_BU
    , (SELECT BU_NAME FROM FUN_ALL_BUSINESS_UNITS_V WHERE BU_ID = PSAAM.BILL_TO_BU_ID) BILL_TOBU
    , HLA_SHIP.LOCATION_CODE SHIP_TO_LOCATION
    , HLA_BILL.LOCATION_CODE BILL_TO_LOCATION
    , PSAAM.ALLOW_AWT_FLAG USE_WITHHOLDING_TAX
    , PSAAM.AWT_GROUP_ID WITHHOLDING_TAX_GROUP
    , GCC.SEGMENT1 || '.' || GCC.SEGMENT2 || '.' || GCC.SEGMENT3 || '.' || GCC.SEGMENT4 || '.' || GCC.SEGMENT5 || '.' || GCC.SEGMENT6 || '.' || GCC.SEGMENT7 || '.' || GCC.SEGMENT8 LIABILITY_DISTRIBUTION
    , GCC2.SEGMENT1 || '.' || GCC2.SEGMENT2 || '.' || GCC2.SEGMENT3 || '.' || GCC2.SEGMENT4 || '.' || GCC2.SEGMENT5 || '.' || GCC2.SEGMENT6 || '.' || GCC2.SEGMENT7 || '.' || GCC2.SEGMENT8 PREPAYMENT_DISTRIBUTION
    , GCC1.SEGMENT1 || '.' || GCC1.SEGMENT2 || '.' || GCC1.SEGMENT3 || '.' || GCC1.SEGMENT4 || '.' || GCC1.SEGMENT5 || '.' || GCC1.SEGMENT6 || '.' || GCC1.SEGMENT7 || '.' || GCC1.SEGMENT8 BILL_PAYABLE_DISTRIBUTION
    , PSAAM.INACTIVE_DATE
    , PSAAM.DISTRIBUTION_SET_ID DISTRIBUTION_NAME
FROM
    POZ_SUPPLIERS_V PSV,
    POZ_SUPPLIER_SITES_V PSSV,
    POZ_SITE_ASSIGNMENTS_ALL_M PSAAM,
    POZ_SUPPLIER_SITES_ALL_M PSSAM,
    HR_LOCATIONS HLA_SHIP,
    HR_LOCATIONS HLA_BILL,
    GL_CODE_COMBINATIONS GCC,
    GL_CODE_COMBINATIONS GCC1,
    GL_CODE_COMBINATIONS GCC2,
    FUN_ALL_BUSINESS_UNITS_V FABUV
WHERE 1 = 1
    AND PSV.VENDOR_ID = PSSV.VENDOR_ID
    AND PSAAM.VENDOR_SITE_ID = PSSV.VENDOR_SITE_ID
    AND PSSAM.VENDOR_SITE_ID = PSAAM.VENDOR_SITE_ID
    AND HLA_SHIP.LOCATION_ID(+) = PSAAM.SHIP_TO_LOCATION_ID
    AND HLA_BILL.LOCATION_ID(+) = PSAAM.BILL_TO_LOCATION_ID
    AND GCC.CODE_COMBINATION_ID(+) = PSAAM.ACCTS_PAY_CODE_COMBINATION_ID
    AND GCC1.CODE_COMBINATION_ID(+) = PSAAM.FUTURE_DATED_PAYMENT_CCID
    AND GCC2.CODE_COMBINATION_ID(+) = PSAAM.PREPAY_CODE_COMBINATION_ID
    AND FABUV.BU_ID = PSSAM.PRC_BU_ID
	--AND ROWNUM < 100
	--AND PSV.VENDOR_NAME = 'AMERICAN EXPRESS COMPANY MEXICO SA DE CV'
	--AND PSV.VENDOR_NAME IN( :P_Proveedor)
    AND (PSV.VENDOR_NAME IN (:P_Proveedor) OR 'ALL' IN (:P_Proveedor || 'All'))

ORDER BY PSV.VENDOR_NAME ASC