SELECT PSCV.PARTY_NAME SUPPLIER_NAME
	, PSCV.PREFIX
	, PSCV.FIRST_NAME
	, PSCV.MIDDLE_NAME
	, PSCV.LAST_NAME
	, PSCV.TITLE
	, PSCV.ADMINISTRATIVE_CONTACT
	, PSCV.EMAIL_ADDRESS
	, PSCV.PHONE_COUNTRY_CODE
	, PSCV.AREA_CODE
	, PSCV.PHONE
	, PSCV.MOBILE
	, PSCV.MOBILE_COUNTRY_CODE
	, PSCV.MOBILE_AREA_CODE
FROM POZ_SUPPLIER_CONTACTS_V PSCV
WHERE 1 = 1
	--AND ROWNUM < 100
	--AND PSCV.PARTY_NAME IN ( :P_Proveedor)
    AND (PSCV.PARTY_NAME IN (:P_Proveedor) OR 'ALL' IN (:P_Proveedor || 'All'))
