SELECT PSCV.PARTY_NAME SUPPLIER_NAME
	, HPS.PARTY_SITE_NAME
	, PSCV.PREFIX
	, PSCV.FIRST_NAME
	, PSCV.LAST_NAME
	, PSCV.EMAIL_ADDRESS
FROM POZ_SUPPLIERS_V PSV
	, POZ_SUPPLIER_SITES_V PSSV
	, HZ_PARTY_SITES HPS
	, POZ_SUPPLIER_CONTACTS_V PSCV
WHERE 1 = 1
	AND PSV.VENDOR_ID = PSSV.VENDOR_ID
	AND PSSV.VENDOR_SITE_ID = HPS.PARTY_SITE_ID
	AND HPS.STATUS = 'A'
	AND PSSV.VENDOR_SITE_ID =PSCV.VENDOR_SITE_ID
	--AND ROWNUM < 100
	--AND PSV.VENDOR_NAME = 'FINSA SA DE CV'
	--AND PSCV.PARTY_NAME IN (:P_Proveedor)
    AND (PSCV.PARTY_NAME IN (:P_Proveedor) OR 'ALL' IN (:P_Proveedor || 'All'))
