SELECT HP.PARTY_NAME
	, PS.SEGMENT1 SUPPLIER_NUMBER
	, PS.ORGANIZATION_TYPE_LOOKUP_CODE TAX_ORGANIZATION_TYPE
	, PS.VENDOR_TYPE_LOOKUP_CODE SUPPLIER_TYPE
	, PS.END_DATE_ACTIVE INACTIVE_DATE
	, PS.BUSINESS_RELATIONSHIP
	, PS.CUSTOMER_NUM CUSTOMER_NUMBER
	, PS.TAXPAYER_COUNTRY
	, PS.ATTRIBUTE1
	, PS.ATTRIBUTE2
	, PS.ATTRIBUTE3
	, PS.ATTRIBUTE4
	, PS.ATTRIBUTE5
	, PS.ATTRIBUTE6
	, PS.ATTRIBUTE7
	, PS.ATTRIBUTE8
	--, PSSAM.TERMS_ID
	, PS.VENDOR_ID
FROM POZ_SUPPLIERS PS
	, HZ_PARTIES HP
	--, POZ_SUPPLIER_SITES_ALL_M PSSAM
WHERE 1 = 1
	AND PS.PARTY_ID = HP.PARTY_ID
	AND PS.END_DATE_ACTIVE IS NULL
    AND (HP.PARTY_NAME IN (:P_Proveedor) OR 'ALL' IN (:P_Proveedor || 'All'))
	--AND (PAPF.PERSON_NUMBER IN (:P_NUMERO_PERSONA) OR 'All' IN (:P_NUMERO_PERSONA || 'All'))

	--AND ROWNUM < 100
	--AND PS.VENDOR_ID = PSSAM.VENDOR_ID
	--AND HP.PARTY_NAME IN (:P_Proveedor) --'AMERICAN EXPRESS COMPANY MEXICO SA DE CV' 
ORDER BY HP.PARTY_NAME ASC