WITH PREPAY_INVOICE AS (
	SELECT AILA.INVOICE_ID
		, AIAA.INVOICE_NUM PREPAYMENT_NUMBER
		, AILA.PREPAY_LINE_NUMBER
		, ( - 1 ) * ( AILA.AMOUNT - nvl(AILA.INCLUDED_TAX_AMOUNT, 0) ) PREPAYMENT_AMOUNT_APLIED
		, AIAA.GL_DATE PREPAYMENT_ACCOUNTING_DATE
	FROM AP_INVOICE_LINES_ALL AILA
		, AP_INVOICES_ALL AIAA
	WHERE 1 = 1
		AND AILA.LINE_TYPE_LOOKUP_CODE = 'PREPAY'
		AND AILA.PREPAY_INVOICE_ID = AIAA.INVOICE_ID(+)
)
, APPLIED_PREPAYMENTS AS (
	SELECT AIA.INVOICE_ID
		, AILA.INVOICE_AMOUNT AS PREPAYMENT_AMOUNT
	FROM AP_INVOICES_ALL AIA
		, AP_PREPAY_HISTORY_ALL APHA
		, AP_INVOICES_ALL AILA
	WHERE 1 = 1
		AND AIA.INVOICE_ID = APHA.INVOICE_ID
		AND APHA.PREPAY_INVOICE_ID = AILA.INVOICE_ID
		AND AIA.INVOICE_TYPE_LOOKUP_CODE = 'STANDARD'
		AND AILA.INVOICE_TYPE_LOOKUP_CODE = 'PREPAYMENT'
)

SELECT AIA.INVOICE_ID
	, HOUFT.NAME BUSINESS_UNIT
	, AIA.INVOICE_NUM
	, AIA.SOURCE
	, AIA.INVOICE_AMOUNT
	, AIA.INVOICE_DATE
	, HP.PARTY_NAME SUPPLIER_NAME
	, HP.PARTY_NUMBER SUPPLIER_NUMBER
	, PSSAM.VENDOR_SITE_CODE SUPPLIER_SITE 
	, AIA.INVOICE_CURRENCY_CODE
	, AIA.PAYMENT_CURRENCY_CODE
	, AIA.DESCRIPTION
	--, IMPORT_SET
	, AIA.INVOICE_TYPE_LOOKUP_CODE
	, XEP.NAME LEGAL_ENTITY
	, ATT.NAME PAYMENT_TERMS
	, AIA.TERMS_DATE
	, AIA.GL_DATE ACCOUNTING_DATE
	, AIA.PAYMENT_METHOD_LOOKUP_CODE
	, AIA.PAY_GROUP_LOOKUP_CODE PAY_GROUP
	--, PAY_ALONE
	, AIA.DISCOUNT_AMOUNT_TAKEN DISCOUNTABLE_AMOUNT
	, P_I.PREPAYMENT_NUMBER
	, P_I.PREPAY_LINE_NUMBER PREPAYMENT_LINE_NUMBER
	, P_I.PREPAYMENT_AMOUNT_APLIED PREPAYMENT_APPLICATION_AMOUNT
	, P_I.PREPAYMENT_ACCOUNTING_DATE 
	, DECODE(NVL(TO_CHAR(P_I.INVOICE_ID),'N'),'N','N','Y') INVOICE_INCLUDES_PREPAYMENT
	--, CONVERSION_RATE_TYPE
	--, CONVERSION_DATE
	--, CONVERSION_RATE
	--, LIABILITY_COMBINATION
	--, PAYMENT_PRIORITY
	--, WITHHOLDING_TAX_GROUP
	--, SHIP_TO_LOCATION
	--, TAXATION_COUNTRY
	--, CALCULATE_TAX_DURING_IMPORTING
	--, ADD_TAX_TO_INVOICE_AMOUNT
	, AIA.ATTRIBUTE1
	, AIA.ATTRIBUTE2
	, AIA.ATTRIBUTE_DATE1
	, HP2.PARTY_NAME REMIT_TO_SUPPLIER
	, HP2.PARTY_NUMBER REMIT_TO_SUPPLIER_NUMBER
	, HL.ADDRESS1 REMIT_TO_ADDRESS_NAME
	, AP_INVOICES_PKG.GET_POSTING_STATUS(AIA.INVOICE_ID) ACCOUNTING_STATUS
	, AIA.PAYMENT_STATUS_FLAG
	, AIA.EXCHANGE_RATE CONVERSION_RATE
	, AIA.EXCHANGE_RATE_TYPE CONVERSION_RATE_TYPE
	, AIA.EXCHANGE_DATE CONVERSION_DATE
	, CASE 
		WHEN AP_INVOICES_PKG.GET_POSTING_STATUS(AIA.INVOICE_ID) = 'Y' THEN 'Posteada' 
		WHEN AP_INVOICES_PKG.GET_POSTING_STATUS(AIA.INVOICE_ID) = 'N' THEN 'No Posteada' 
		WHEN AP_INVOICES_PKG.GET_POSTING_STATUS(AIA.INVOICE_ID) = 'S' THEN 'Seleccionada' 
		WHEN AP_INVOICES_PKG.GET_POSTING_STATUS(AIA.INVOICE_ID) = 'P' THEN 'Parcialmente Posteada' 
	END AS POSTING_STATUS	
	, CASE 
		WHEN AIA.PAYMENT_STATUS_FLAG = 'Y' THEN 'Pagada'
		WHEN AIA.PAYMENT_STATUS_FLAG = 'N' THEN 'No pagada'
		WHEN AIA.PAYMENT_STATUS_FLAG = 'P' THEN 'Parcialmente Pagada'
	END AS PAYMENT_STATUS
	, GCC.SEGMENT1 || '.' || GCC.SEGMENT2 || '.' || GCC.SEGMENT3 || '.' || GCC.SEGMENT4 || '.' || GCC.SEGMENT5 LIABILITY_DISTRIBUTION
	, APSA.AMOUNT_REMAINING UNPAID_AMOUNT
	, AP.PREPAYMENT_AMOUNT
	--, AILA.LINE_TYPE_LOOKUP_CODE	
FROM AP_INVOICES_ALL AIA
	, AP_TERMS_B ATB
	, AP_TERMS_TL ATT
	, POZ_SUPPLIERS PS
	, HZ_PARTIES HP
	, HZ_PARTY_SITES HPS
	, HR_ALL_ORGANIZATION_UNITS_F HAOUF
	, HR_ORGANIZATION_UNITS_F_TL HOUFT
	, PREPAY_INVOICE P_I
	, POZ_SUPPLIER_SITES_ALL_M PSSAM
	, XLE_ENTITY_PROFILES XEP
	, POZ_SUP_THIRDPARTY_PAYMENT_REL PSTPR
	, HZ_PARTIES HP2
	, HZ_PARTY_SITES HPS2	
	, HZ_LOCATIONS HL
	, FUN_ALL_BUSINESS_UNITS_V FABUV
	, GL_LEDGERS GL
	, GL_CODE_COMBINATIONS GCC
	, AP_PAYMENT_SCHEDULES_ALL APSA
	, APPLIED_PREPAYMENTS AP
	--, AP_INVOICE_LINES_ALL AILA
	--, AP_INVOICES_ALL AIAA	
WHERE 1 = 1
	--UNIONES
	AND AIA.TERMS_ID = ATB.TERM_ID
	AND ATB.TERM_ID = ATT.TERM_ID
	AND AIA.VENDOR_ID = PS.VENDOR_ID
	AND PS.PARTY_ID = HP.PARTY_ID
	AND HP.PARTY_ID = HPS.PARTY_ID
	AND AIA.ORG_ID = HAOUF.ORGANIZATION_ID
	AND HAOUF.ORGANIZATION_ID = HOUFT.ORGANIZATION_ID
	AND HOUFT.LANGUAGE = USERENV('LANG')
	AND ATT.LANGUAGE = USERENV('LANG')
	AND AIA.INVOICE_ID = P_I.INVOICE_ID(+)
	AND AIA.VENDOR_SITE_ID = PSSAM.VENDOR_SITE_ID
	AND AIA.LEGAL_ENTITY_ID = XEP.LEGAL_ENTITY_ID
	AND PSSAM.VENDOR_SITE_ID = PSTPR.VENDOR_SITE_ID (+)
	AND PSTPR.REMIT_TO_SUPPLIER_ID = HP2.PARTY_ID (+)
	AND PSTPR.REMIT_TO_ADDRESS_ID = HPS2.PARTY_SITE_ID(+)
	AND HPS2.LOCATION_ID = HL.LOCATION_ID(+)
	AND (AP_INVOICES_PKG.GET_POSTING_STATUS(AIA.INVOICE_ID) != 'Y'
		OR AIA.PAYMENT_STATUS_FLAG IN ('P','N'))
	AND AIA.ORG_ID = FABUV.BU_ID
	AND AIA.SET_OF_BOOKS_ID = GL.LEDGER_ID(+)
	AND AIA.ACCTS_PAY_CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID(+)
	AND AIA.INVOICE_ID = APSA.INVOICE_ID
	AND AIA.INVOICE_ID = AP.INVOICE_ID(+)
	--AND AIA.INVOICE_ID = AILA.INVOICE_ID
	--AND AILA.LINE_TYPE_LOOKUP_CODE(+) = 'PREPAY'
	--AND AILA.PREPAY_INVOICE_ID = AIAA.INVOICE_ID(+)
	
	--FILTROS
	--AND AIA.INVOICE_NUM = 'OC51190 FD 4419'--'F80006358669 SEP 25'
	AND AIA.INVOICE_DATE BETWEEN :P_FECHA_INICIO AND :P_FECHA_FIN
	AND FABUV.BU_NAME = NVL(:P_ORGANIZATION,FABUV.BU_NAME) 
	AND GL.NAME = NVL(:P_LEDGER_NAME, GL.NAME)
ORDER BY AIA.CREATION_DATE DESC
