SELECT AILA.INVOICE_ID
	, AILA.LINE_NUMBER
	, AILA.LINE_TYPE_LOOKUP_CODE
	, AILA.AMOUNT
	, AILA.UNIT_PRICE
	, AILA.UNIT_MEAS_LOOKUP_CODE UOM
	, AILA.DESCRIPTION
	, AILA.ITEM_DESCRIPTION
	, PHA.SEGMENT1 PO_NUMBER
	, PLA.LINE_NUM 
	--, PO_SCHEDULE_NUMBER
	--, PO_DISTRIBUTION_NUMBER
	--, PLA.ITEM_DESCRIPTION
	, GCC.SEGMENT1 || '-' || GCC.SEGMENT2 || '-' || GCC.SEGMENT3 || '-' || GCC.SEGMENT4 || '-' || GCC.SEGMENT5 || '-' || GCC.SEGMENT6 || '-' || GCC.SEGMENT7 DISTRIBUTION_COMBINATION
	--, DISTRIBUTION_SET
	, AILA.ACCOUNTING_DATE
	, AILA.TAX_CLASSIFICATION_CODE
	, AILA.TAX
	, AILA.TAX_RATE_CODE
	, AILA.TAX_RATE
	, AAG.NAME
	, AILA.TYPE_1099 WITHHOLDING
FROM AP_INVOICE_LINES_ALL AILA
	, AP_INVOICE_DISTRIBUTIONS_ALL AIDA
	, PO_HEADERS_ALL PHA
	, PO_LINES_ALL PLA
	, PO_DISTRIBUTIONS_ALL PDA
	, GL_CODE_COMBINATIONS GCC
	, AP_AWT_GROUPS AAG
WHERE 1 = 1
	AND AILA.INVOICE_ID = AIDA.INVOICE_ID
	AND AILA.LINE_NUMBER = AIDA.INVOICE_LINE_NUMBER
	AND AILA.PO_HEADER_ID = PHA.PO_HEADER_ID(+)
	AND PHA.PO_HEADER_ID = PLA.PO_HEADER_ID(+)
	AND PLA.PO_HEADER_ID = PDA.PO_HEADER_ID(+)
	AND PLA.PO_LINE_ID = PDA.PO_LINE_ID(+)
	AND AIDA.DIST_CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
	AND AILA.LINE_TYPE_LOOKUP_CODE = 'ITEM'

	AND AILA.AWT_GROUP_ID = AAG.GROUP_ID(+)

